ERP/Controllers/RejestracjaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ERP.Models;

namespace ERP.Controllers
{
    public class RejestracjaController : Controller
    {
        // GET: Rejestracja
        public ActionResult Index()
        {
            return View();
        }

        // GET: Rejestracja/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Rejestracja/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Rejestracja/Create
        [HttpPost]
        public ActionResult Create(UserViewModel model)
        {
            try
            {
                AplikacjeInternetoweEntities1 db = new AplikacjeInternetoweEntities1();
                Uzytkownicy uzytkownik = new Uzytkownicy();

                uzytkownik.nazwa = model.nazwa;
                uzytkownik.haslo = model.haslo;
                uzytkownik.ulica = model.ulica;
                uzytkownik.kodpocz = model.kodpocz;
                uzytkownik.miejscowosc = model.miejscowosc;
                uzytkownik.rola = "uzytkownik";
                uzytkownik.nip = model.nip;

                var userExists = db.Uzytkownicy.FirstOrDefault(x => x.nazwa == uzytkownik.nazwa);

                if (userExists == null)
                {
                    db.Uzytkownicy.Add(uzytkownik);
                    db.SaveChanges();
                    return View("RejestracjaDone");
                }
                else
                {
                    return View("UserExist");
                }
            }
            catch
            {
                return View("RejestracjaFailed");
            }
        }

        // GET: Rejestracja/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Rejestracja/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return View();
            }
        }

        // GET: Rejestracja/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Rejestracja/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ERP/Views/Rejestracja/RejestracjaDone.cshtml
<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>

<div class="modal-fade" id="ModalRejestracjaDone">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                Zarejestrowano! Za chwilę zostaniesz przekierowany do panelu logowania...
            </div>
        </div>
    </div>
</div>

<script>
    window.setTimeout(function () {
        window.location.href = 'http://localhost:52623/Uzytkownicy/login';
    }, 4000);
</script>

ERP/Views/Rejestracja/RejestracjaFailed.cshtml
@model ERP.Models.Uzytkownicy

@{
    ViewBag.Title = "RejestracjaFailed";
}

<h2>Nie udało się :(</h2>

ERP/Views/Rejestracja/UserExist.cshtml
@{
    ViewBag.Title = "UserExist";
}

<h2>Niestety, taki użytkownik już istnieje.</h2>

<div>
    @Html.ActionLink("Spróbuj ponownie", "Rejestracja", "Home")
</div>