ERP/Models/Uzytkownicy.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Uzytkownicy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Uzytkownicy()
        {
            this.DkPz = new HashSet<DkPz>();
            this.DkSp = new HashSet<DkSp>();
            this.DkWz = new HashSet<DkWz>();
            this.DkZk = new HashSet<DkZk>();
            this.ZMO = new HashSet<ZMO>();
            this.ZMW = new HashSet<ZMW>();
        }
    
        public long id { get; set; }
        public string nazwa { get; set; }
        public string haslo { get; set; }
        public string rola { get; set; }
        public string ulica { get; set; }
        public string kodpocz { get; set; }
        public string miejscowosc { get; set; }
        public string nip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DkPz> DkPz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DkSp> DkSp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DkWz> DkWz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DkZk> DkZk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZMO> ZMO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZMW> ZMW { get; set; }
    }
}

ERP/Controllers/UzytkownicyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ERP.Models;
using PagedList;

namespace ERP.Controllers
{
    public class UzytkownicyController : Controller
    {
        public ActionResult Index()//Index(int? page)
        {
            AplikacjeInternetoweEntities1 db = new AplikacjeInternetoweEntities1();

            List<Uzytkownicy> uzytkownicyList = new List<Uzytkownicy>();
            uzytkownicyList = db.Uzytkownicy.ToList();

            //Uzytkownicy uzytkownik = db.Uzytkownicy.SingleOrDefault(x => x.id == id);
            List<UserViewModel> vmList = new List<UserViewModel>();

            foreach (var x in uzytkownicyList)
            {
                UserViewModel vm = new UserViewModel();

                vm.id = x.id;
                vm.haslo = x.haslo;
                vm.nazwa = x.nazwa;
                vm.rola = x.rola;
                vm.ulica = x.ulica;

                vmList.Add(vm);
            }

            //int pageSize = 3;
           // int pageNumber = (page ?? 1);
            ViewBag.Uzytkownicy = vmList;
            //return View(vmList.ToPagedList(pageNumber, pageSize));
            return View();
        }


        public ActionResult Login()
        {
            if (Session["username"] != null)
            {
                return RedirectToAction("Index", "Home", new { username = Session["username"].ToString() });
            }
            else {
                return View();
            }
        }

        [HttpPost]
        public ActionResult Login(UserViewModel model)
        {
            AplikacjeInternetoweEntities1 db = new AplikacjeInternetoweEntities1();

            var userLoggedIn = db.Uzytkownicy.SingleOrDefault(x => x.nazwa == model.nazwa && x.haslo == model.haslo);


   
            if (userLoggedIn != null)
            {
                ViewBag.message = "Logged In";
                ViewBag.triedOnce = "true";
                ViewBag.username = model.nazwa;

                Session["username"] = model.nazwa;

                return View("LoggedIn");
            }
            else
            {
                return View("LoginFailed");
            }

            //if (model.UserName == "xyz" && model.Password == "xyz")
            //{
            //    Session["uname"] = model.UserName;
            //    Session.Timeout = 10;
            //    return RedirectToAction("Index");
            //}

            
        }

        [HttpGet]
        public ActionResult Edit(long UserId)
        {
            AplikacjeInternetoweEntities1 db = new AplikacjeInternetoweEntities1();

           // UserViewModel userModel = new UserViewModel();

            var userModel = db.Uzytkownicy.SingleOrDefault(x => x.id == UserId);
            UserViewModel uViewModel = new UserViewModel();


            if (userModel != null) {
                uViewModel.id = userModel.id;
                uViewModel.nazwa = userModel.nazwa;
                uViewModel.haslo = userModel.haslo;
                uViewModel.kodpocz = userModel.kodpocz;
                uViewModel.miejscowosc = userModel.miejscowosc;
                uViewModel.rola = userModel.rola;

            }
            ViewBag.Uzytkownik = uViewModel;
            return View("Edit");
        }



        [HttpPost]
        public JsonResult UserDelete(long UserId)
        {
            AplikacjeInternetoweEntities1 db = new AplikacjeInternetoweEntities1();

            bool result = false;

            Uzytkownicy user = db.Uzytkownicy.SingleOrDefault(x => x.id == UserId);

            if (user != null) {
                try
                {
                    db.Uzytkownicy.Remove(user);
                    db.SaveChanges();
                    result = true;
                }
                catch (Exception e)
                {
                    e.ToString();
                }
            }

            return Json(result, JsonRequestBehavior.AllowGet);

        }
    }
}

ERP/Views/Uzytkownicy/Edit.cshtml
@model ERP.Models.Uzytkownicy

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Uzytkownicy</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.haslo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.haslo, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.rola, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.rola, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.rola, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ulica, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ulica, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ulica, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kodpocz, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kodpocz, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kodpocz, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.miejscowosc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.miejscowosc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.miejscowosc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nip, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nip, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nip, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Zapisz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ERP/Views/Uzytkownicy/Index.cshtml
@model ERP.Models.UserViewModel
@*@using PagedList.Mvc
    @model PagedList.IPagedList<ERP.Models.Uzytkownicy>*@

<h2>@ViewBag.Title</h2>
<h3>@ViewBag.Message</h3>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>



<style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }
</style>


@if (ViewBag.Uzytkownicy != null)
{
    <table>
        <tr>
            <th>Nazwa</th>
            <th>Hasło</th>
            <th>Rola</th>
            <th>Ulica</th>
        </tr>
        @foreach (var item in ViewBag.Uzytkownicy)
        {
            <tr id="row_@item.id">
                <th><b>@item.nazwa</b></th>
                <th>@item.haslo</th>
                <th>@item.rola</th>
                <th>@item.ulica</th>
                <th>@item.id</th>
                <th><a href="#" class="btn btn-danger" onclick="ConfirmDelete(@item.id)"><i class="glyphicon glyphicon-trash"></i></a></th>
                <th><a href="@Url.Action("Edit","Uzytkownicy", new { UserId = item.id})" class="btn btn-info"><i class="glyphicon glyphicon-edit"></i></a></th>
            </tr>
        }
    </table>

    <input type="hidden" id="hiddenId" />

    <div class="modal fade" id="deleteModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h3 class="modal-title">Usuń użytkownika</h3>
                </div>
                <div class="modal-body">
                    <h4>Jesteś pewien? </h4>
                    <div style="text-align:center;display:none" id="loaderDiv">
                        <img src="~/Content/InternetSlowdown_Day.gif" width="150" />
                    </div>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-default" data-dismiss="modal">Anuluj</a>
                    <a href="#" class="btn btn-success" onclick="UsunUzytkownika()">Potwierdź</a>
                </div>
            </div>
        </div>
    </div>

    @*<div class="modal fade" id="editModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <a href="#" class="close" data-dismiss="modal">&times;</a>
                    <h3 class="modal-title">Edycja użytkownika</h3>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-default" data-dismiss="modal">Anuluj</a>
                    <a href="#" class="btn btn-success" onclick="UsunUzytkownika()">Potwierdź</a>
                </div>
            </div>
        </div>
    </div>*@
}
else
{
    <h2> Brak wyników!</h2>
}

@*<table>
        <div style="margin:5px;">
            Page @(Model.PageCount < Model.PageNumber ? 0:Model.PageNumber) of @Model.PageCount
            @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, CurrentFilter = ViewBag.CurrentFilter}))
        </div>
    </table>*@

<script>

    var ConfirmDelete = function (UserId) {
        $("#hiddenId").val(UserId);
        $("#deleteModal").modal('show');
    }



    var UsunUzytkownika = function () {

        $("#loaderDiv").show();

        var IdUsera = $("#hiddenId").val();

        $.ajax({
            type: "POST",
            url: "/Uzytkownicy/UserDelete",
            data: { UserId: IdUsera },
            success: function (result) {
                $("#loaderDiv").hide();
                $("#deleteModal").modal('hide');
                $("#row_" + IdUsera).remove();
            }

        })
    }

    //var EdycjaUzytkownika = function (UserId) {

    //    var IdUsera = UserId;

    //    $.ajax({
    //        type: "GET",
    //        url: "/Uzytkownicy/Edit",
    //        data: { UserId: IdUsera },
    //        success: function (result) {
    //        }

    //    })
    //}
</script>

ERP/Views/Uzytkownicy/LoggedIn.cshtml
@{
    ViewBag.Title = "LoggedIn";
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/bootstrap.min.js"></script>

<h2>Witaj, @ViewBag.username! Za chwilę zostaniesz przekierowany na stronę główną.</h2>

<script>
    window.setTimeout(function () {
        window.location.href = 'http://localhost:52623/';
    }, 4000);
</script>

ERP/Views/Uzytkownicy/Login.cshtml
@model ERP.Models.UserViewModel

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nazwa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nazwa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nazwa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.haslo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.haslo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.haslo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ERP/Views/Uzytkownicy/LoginFailed.cshtml
@{
    ViewBag.Title = "LoginFailed";
}

<h2>LoginFailed</h2>